# Generated by Django 5.2.4 on 2025-07-14 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extraction", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extractionjob",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="record_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="extractionjob",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExtractedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_from_service", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=255)),
                ("last_name", models.CharField(blank=True, max_length=255)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="extraction.extractionjob",
                    ),
                ),
            ],
            options={
                "ordering": ["id_from_service"],
                "unique_together": {("job", "id_from_service")},
            },
        ),
    ]
